# Generated by Django 5.1.5 on 2025-05-07 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlaggedTransaction',
        ),
    ]
