# Generated by Django 5.1.5 on 2025-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='accountlimit',
            name='monthly_withdrawal_limit',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_images/default-profile-image.png', null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('SUPPOT', 'Support')], default='CUSTOMER', max_length=9),
        ),
    ]
