# Generated by Django 5.1.5 on 2025-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_account_number_alter_accounttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='max_single_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='AccountLimit',
        ),
    ]
