# Generated by Django 5.1.5 on 2025-04-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_roles_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='accounts.account'),
        ),
    ]
