# Generated by Django 5.1.5 on 2025-05-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_accountupgraderequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='account',
        ),
    ]
