# Generated by Django 5.1.5 on 2025-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_accounttype_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='daily_transfer_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='max_single_transfer_amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
        ),
    ]
