# Generated by Django 5.1.5 on 2025-05-05 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_daily_transfer_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountupgraderequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='accountupgraderequest',
            name='rejected_by',
        ),
        migrations.AddField(
            model_name='accountupgraderequest',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
