# Generated by Django 5.1.5 on 2025-05-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_accountupgraderequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountupgraderequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=10),
        ),
    ]
