# Generated by Django 5.1.5 on 2025-05-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accountupgraderequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
