# Generated by Django 5.1.5 on 2025-04-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_transaction_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_flow',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10),
        ),
    ]
