# Generated by Django 5.1.5 on 2025-04-26 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_accounttype_daily_transfer_limit_and_more'),
        ('transactions', '0005_transactionlimitupgraderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlimitupgraderequest',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_upgrade_requests', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='transactionlimitupgraderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
