# Generated by Django 5.1.5 on 2025-05-04 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionlimitupgraderequest_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlimitupgraderequest',
            name='user',
        ),
        migrations.AddField(
            model_name='transactionlimitupgraderequest',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actioned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
