# Generated by Django 5.1.5 on 2025-05-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_transactionlimitupgraderequest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlimitupgraderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
