# Generated by Django 5.1.5 on 2025-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transactionlimitupgraderequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlimitupgraderequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
