# Generated by Django 5.1.5 on 2025-05-07 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_transaction_flagged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='flagged',
        ),
    ]
