# Generated by Django 5.1.5 on 2025-05-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_transaction_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedtransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('flagged', 'Flagged')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('flagged', 'Flagged')], default='pending', max_length=10),
        ),
    ]
