# Generated by Django 5.1.5 on 2025-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_flaggedtransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedtransaction',
            name='status',
            field=models.CharField(choices=[('flagged', 'Flagged'), ('unflagged', 'Unflagged'), ('rejected', 'Rejected')], default='flagged', max_length=10),
        ),
    ]
