# Generated by Django 5.1.5 on 2025-04-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='transaction_flow',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
