# Generated by Django 5.1.5 on 2025-05-04 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_transaction_flow_and_more'),
        ('transactions', '0006_alter_transactionlimitupgraderequest_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
